application:
  autowire:
    commands:
      forced:
        'extend:example':
          class: '\Drupal\Console\Extend\Command\ExampleCommand'
        'extend:example:container:aware':
          class: '\Drupal\Console\Extend\Command\ExampleContainerAwareCommand'
      name: {}
